name: learn-github-actions
on: [push]

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'


      - name: Install Dependecies
        run: pip install -r requirements.txt

      - name: Run test
        run: python -m unittest tests/test_add.py
